### ISSUE TITLE
Field is required is red even after field is filled in

### ISSUE THREAD

**Issue by banovotz** [Baasic/baasic-dashboard#10]
#### Note
There is a text "field is required" for article body even after user enters some text in article body
#### Img
<img src="https://api.baasic.com/beta/system/dashboard/feedback/pero/Field_is_required_is_red_even_after_field_is_filled_in.png" alt="Image"/>
#### Url
https://dashboard.baasic.com/apps/pero/article/add
###### App Code Name
Mozilla
###### App Name
Netscape
###### App Version
5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
###### Cookie Enabled
True
###### On Line
True
###### Platform
MacIntel
###### User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
###### Plugins
* Widevine Content Decryption Module
* Chrome PDF Viewer
* Shockwave Flash
* Chrome Remote Desktop Viewer
* Native Client
* Chrome PDF Viewer

**Comment by andrejmlinarevic** [comment]
@banovotz Thanks for the feedback, the issue is tested and resolved on live and staging.
