### ISSUE TITLE
Welcome message ccupies great part of dashboard

### ISSUE THREAD

**Issue by banovotz** [Baasic/baasic-dashboard#14]
#### Note
Welcome occupies great part of dashboard(s). All important stuff like app list is below this big info field. If user has a resized browser window (which is often at Macs) he may not even be able to see his apps. 

Expected:
The welcome section at dashboard is not so large. 
#### Img
<img src="https://api.baasic.com/beta/system/dashboard/feedback/system/Welcome_message_ccupies_great_part_of_dashboard.png" alt="Image"/>
#### Url
https://dashboard.baasic.com/
###### App Code Name
Mozilla
###### App Name
Netscape
###### App Version
5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
###### Cookie Enabled
True
###### On Line
True
###### Platform
MacIntel
###### User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
###### Plugins
* Widevine Content Decryption Module
* Chrome PDF Viewer
* Shockwave Flash
* Chrome Remote Desktop Viewer
* Native Client
* Chrome PDF Viewer

**Comment by khorvat** [comment]
This has been improved and will be available in next build.
