### ISSUE TITLE
Search menu is not obviously a searchbox

### ISSUE THREAD

**Issue by banovotz** [Baasic/baasic-dashboard#15]
#### Note
Search menu looks like a label and is not obviously a searchbox.

Expected:
There is a magnifier icon next to a search box or the box is different color then rest of the menu. 
#### Img
<img src="https://api.baasic.com/beta/system/dashboard/feedback/system/Search_menu_is_not_obviously_a_searchbox.png" alt="Image"/>
#### Url
https://dashboard.baasic.com/payment
###### App Code Name
Mozilla
###### App Name
Netscape
###### App Version
5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
###### Cookie Enabled
True
###### On Line
True
###### Platform
MacIntel
###### User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
###### Plugins
* Widevine Content Decryption Module
* Chrome PDF Viewer
* Shockwave Flash
* Chrome Remote Desktop Viewer
* Native Client
* Chrome PDF Viewer

**Comment by khorvat** [comment]
This has been improved and will be available in next build.
